spring:
  mail:
    username: 1091164612@qq.com
    password: kxojqenwanyjjbde
    host: smtp.qq.com
    properties:    # 开启加密验证
      main:
        smtl:
          ssl:
            enabled: true
server:
  port: 8080
